var Place =
    [
        {"key":"1",
        "category":"place",
        "name":"Cox’s Bazar",
        "shortd":"Cox’s Bazar is a town on the southeast coast of Bangladesh. It’s known for its very long, sandy beachfront, stretching from Sea Beach in the north to Kolatoli Beach in the south.",
        "longd":"Cox's Bazar is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach. It is located 150 km (93 mi) south of the city of Chittagong. Cox's Bazar is also known by the name Panowa, which translates literally as 'yellow flower'. Another old name was Palongkee",
        "img":"https://i.postimg.cc/mgvM1FyD/1-Sundarban-Home-BG.png",
      },
      {"key":"2",
        "category":"place",
        "name":"Sreemangal",
        "shortd":"Sreemangal has an average literacy rate of 29.8% (7+ years), and the national average of 32.4% literate. Hindus constitute around 50% of the total population.",
        "longd":"It is said the name Sreemangal (or Srimangal) is named after Sri Das and Mangal Das; two brothers who settled on the banks of the Hail Haor.[2] A copper plate of Raja Marundanath from the 11th century was found in Kalapur. During an excavation at Lamua, an ancient statue of Ananta Narayan was dug out. In 1454, the Nirmai Shiva Bari was built and still stands today. Srimangal thana was established in 1912.",
        "img":"https://i.postimg.cc/L6hZyVy5/2-Sreemongol.png",
      }, 
      {"key":"3",
        "category":"place",
        "name":"Sundarban",
        "shortd":"The Sundarbans is a mangrove area in the delta formed by the confluence of the Ganges, Brahmaputra and Meghna Rivers in the Bay of Bengal.",
        "longd":"The Sundarbans is a mangrove area in the delta formed by the confluence of the Ganges, Brahmaputra and Meghna Rivers in the Bay of Bengal. It spans from the Hooghly River in India's state of West Bengal to the Baleswar River in Bangladesh. It comprises closed and open mangrove forests, agriculturally used land, mudflats and barren land, and is interse.cted by multiple tidal streams and channels",
        "img":"https://i.postimg.cc/qR03jVYH/3-sundorbon.png",
      },
      {"key":"4",
        "category":"room",
        "name":"Light bright airy stylish apt & safe peaceful stay",
        "shortd":"4 guests 2 bedrooms 2 beds 2 baths",
        "longd":"Wif Air conditioning Kitchen Cancellation fexibility availiable",
        "img":"https://i.postimg.cc/wMyTk104/Rectangle-26.png",
        "price" : "34",
        "rating" : "4.9(20)",
      },
      {"key":"5",
        "category":"room",
        "name":"Apartment in Lost Panorama",
        "shortd":"4 guests 2 bedrooms 2 beds 2 baths",
        "longd":"Wif Air conditioning Kitchen Cancellation fexibility availiable",
        "img":"https://i.postimg.cc/506VcjDB/02-Rectangle-27.png",
        "price" : "52",
        "rating" : "4.9(20)",
      },
      // {"key":"6",
      //   "category":"room",
      //   "name":"AR Lounge & Pool (r&r + b&b)",
      //   "shortd":"4 guests 2 bedrooms 2 beds 2 baths",
      //   "longd":"Wif Air conditioning Kitchen Cancellation fexibility availiable",
      //   "img":"https://i.postimg.cc/dVqgPLyh/03-Rectangle-28.png",
      //   "price" : "44",
      //   "rating" : "4.9(20)",
      // },
    ];

export default Place;